### ISSUE TITLE
link current/tmp/pids zu shared/tmp/pids anstatt shared/pids

### ISSUE THREAD

**Issue by matzke** [railshoster/railshoster#19]
Hi,

ich bin mir nicht sicher, ob das railshoster gem dafür verantwortlich ist ...!?
- current/tmp/pids -> /home/userXXXX/rails1/shared/pids

sollte ggf. verlinken nach
- current/tmp/pids -> /home/userXXXX/rails1/shared/**tmp**/pids

Das gem delayed_job liefert z.B. folgenden Fehler

```
2014-05-15 15:52:36 executing `delayed_job:restart'
  * executing "cd /home/userXXXX/rails1/current;RAILS_ENV=production script/delayed_job restart"
    servers: ["rho.railshoster.de"]
    [rho.railshoster.de] executing command
 ** [out :: rho.railshoster.de] /home/userXXXX/rails1/shared/bundle/ruby/2.0.0/gems/delayed_job-4.0.1/lib/delayed/command.rb:73:in `mkdir': File exists - /home/userXXXX/rails1/releases/20140515135205/tmp/pids (Errno::EEXIST)
 ** [out :: rho.railshoster.de] from /home/userXXXX/rails1/shared/bundle/ruby/2.0.0/gems/delayed_job-4.0.1/lib/delayed/command.rb:73:in `daemonize'
 ** [out :: rho.railshoster.de] from script/delayed_job:5:in `<main>'
    command finished in 2033ms
failed: "sh -c 'cd /home/userXXXX/rails1/current;RAILS_ENV=production script/delayed_job restart'" on rho.railshoster.de
```

Als workaround kann das Verzeichnis einfach von Hand angelegt werde.

**Comment by mafolz** [comment]
Vielen dank für das Feedback.

Wir schauen nach warum das tmp Verzeichnis beim Initialisieren nicht erstellt wurde.

Grüße,
Matthias Folz
